### ISSUE TITLE
REG_Clavei: cambiar enode

### ISSUE THREAD

**Issue by Coduy** [alastria/alastria-node-besu-directory#5]
Enode de nodo regular REG_Clavei es incorrecto: enode://80755016b52404a6f3655ff327b3754a6ef684b43f5354a4ddd7d7122020637589beaf89e874a040bcb3fc45d1415a53b3acca38b8fe44d95e30acfc9af665ae@137.117.170.193:30303 

Por favor, lo podéis cambiar a: 
enode://70f2ba4804ce2e6b68232f9c277c2abb8a373274ef055eae6175885ba7866802c664ae589c35c1ad1da005cf18122ad02bacce55bcb1561f70699759381e9c1d@127.0.0.1:30303

Gracias!

**Comment by irzinfante** [comment]
Se ha cambiado el enode address de REG_Clavei a enode://70f2ba4804ce2e6b68232f9c277c2abb8a373274ef055eae6175885ba7866802c664ae589c35c1ad1da005cf18122ad02bacce55bcb1561f70699759381e9c1d@137.117.170.193:30303. Se han actualizado los nodos core y se ve que el nodo REG_Clavei está ahora dentro de la red y en proceso de sincronización con la cadena.

Aseguraros de guardar la clave privada del nodo, por favor, para conservar este enode address.

Gracias.
